### PR TITLE
Making a Donut chart with Canvas

### PR DESCRIPTION
**Pull request by UncleFifi**
was able to make a donut chart using pure javascript

### CODE REVIEW

**Comment by UncleFifi** [comment]
fixed merge errors. sorry about that Im new to git. would you please consider my PR with out the tweet? I dont have a twitter account.

**Comment by sophiabrandt** [comment]
@UncleFifi not sure what you mean with tweet? It's not necessary for Hacktoberfest.

**Comment by UncleFifi** [comment]
Would someone kindly add label of "hacktoberfest-accepted" please

**Comment by sophiabrandt** [comment]
No need, the repo is already labeled "Hacktoberfest".

**Comment by UncleFifi** [comment]
Thank you so much!

**Pull request merged**
