### PR TITLE
Add ZaheerCanvas

### PR DESCRIPTION
**Pull request by nk4456542**
Hello, I have added my Artwork, a simple cube. Please merge my pull request, if this looks good.
Thank you

### CODE REVIEW

**Comment by MattCSmith** [comment]
Hey @nk4456542 There is a conflict with this PR I am unable to resolved from my end. 
Any chance you could take a look 🙂

**Comment by nk4456542** [comment]
> Hey @nk4456542 There is a conflict with this PR I am unable to resolved from my end.
> Any chance you could take a look

Working on it. @MattCSmith

**Comment by nk4456542** [comment]
@MattCSmith I have resolved the conflict, and pushed it, can you merge this now. Is this the correct way to send a pull request on merge conflicts because, I am new to this. I am asking this because i have two commits in here, should i amend those commits? or is this fine?

**Comment by MattCSmith** [comment]
@nk4456542 Nope thats exactly how your resolve a merge conflict. 
Nice job 👍 
Merging 🚀

**Pull request merged**
