### PR TITLE
Updated Index.js For jQuery error

### PR DESCRIPTION
**Pull request by funpractice**
Thank You for approving my lightning canvas, but I see that it's not working on canvas creations in which jQuery error is appearing so I removed this error, so please approve my request.

### CODE REVIEW

**Comment by royranger** [comment]
@funpractice Hi! There are some conflicts in your files, you might wanna check them out and resolve them =)

**Comment by funpractice** [comment]
I tried but can't solve the merge problem.... please help me.

**Comment by royranger** [comment]
@funpractice Haha ok! Merge conflicts resolved, gonna merge it

**Comment by funpractice** [comment]
> @funpractice Haha ok! Merge conflicts resolved, gonna merge it

Thank you😊

**Pull request merged**
