### PR TITLE
canvas

### PR DESCRIPTION
**Pull request by Hetul79**

### CODE REVIEW

**Comment by Hetul79** [comment]
Hello sir,I made one pull request in Canvas Creater.But till now my pull
request didn't accepted.so kindly check it.

**Comment by kennithnichol** [comment]
@Hetul79 you are missing the change to actually include this art on the page.
It looks like you added the code to cards.js instead of includes.js

Try and run the project and verify your art shows up.

**Comment by Hetul79** [comment]
> @Hetul79 you are missing the change to actually include this art on the page.
> It looks like you added the code to cards.js instead of includes.js
> 
> Try and run the project and verify your art shows up.

Thank you sir for your advice. I changed what you said. Now can you check once again?

**Review by kennithnichol — APPROVED** [review]
This looks good. Thank you!

**Comment by Hetul79** [comment]
> This looks good. Thank you!

Thank you so much sir....😊😊

**Pull request merged**
